language: ruby
rvm:
  - 2.2.0
gemfile:
  - Gemfile
before_script:
  - gem install bundler
script:
  - travis_wait bundle exec rspec
notifications:
  emails:
    - guitarpopnot330@gmail.com
  on_success: always # default: change
  on_failure: always
